stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared
    deps:
      - data_preparation.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_preparation
  linear_regression:
    cmd: python linear_regression.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - linear_regression.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_validation:
    cmd: python linear_regression_validation.py -id data/prepared/ -im data/models/${linear_regression.model_name}.joblib
    deps:
      - linear_regression_validation.py
      - data/prepared/
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_prod_version:
    cmd: python linear_regression_full.py -id data/prepared/ -od data/models/ -mn ${linear_regression.model_name}
    deps:
      - linear_regression_full.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}_prod.csv
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - linear_regression
  NN_train:
    cmd: python NN.py -id data/prepared -om data/models/nn
    deps:
      - NN.py
      - data/prepared
    outs:
      - data/models/nn
    params:
      - NN_params
  NN_prod_version:
    cmd: python NN_prod_version.py -id data/prepared -om data/models/nn_prod_version
    deps:
      - NN_prod_version.py
      - data/prepared
    outs:
      - data/models/nn_prod_version
    params:
      - NN_params