data_preparation:
  train_test_ratio: 0.7
  train_val_raitio: 0.8
  random_state: 42
linear_regression:
  model_name: 'LinearRegression'
NN_params:
  hidden_layers: [256, 256, 256, 256, 256, 256]  # Количество нейронов в каждом скрытом слое
  activation: 'relu'  # Функция активации для скрытых слоев
  learning_rate: 0.0001
  epochs: 500
