data_preparation:
  train_test_ratio: 0.8
  train_val_ratio: 0.75
  random_state: 42

linear_regression:
  model_name: "linear_regression_model"

bp_model:
  hidden_units: 64
  optimizer: "adam"
  loss: "mean_squared_error"
  epochs: 100
  batch_size: 32
